databases:
  - name: final_capstone_production
    databaseName: final_capstone_production
    user: final_capstone

services:
  - type: web
    name: final_capstone
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
          fromDatabase:
          name: final_capstone_production
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false